/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5c0c76e7-b9bd-42d0-9815-5cec71cb1a35",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_eJYfSgJLR",
    "aws_user_pools_web_client_id": "7t841qhglv5b6gjfco3lari10i",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "apiae8f3a94",
            "endpoint": "https://t5soonibm8.execute-api.us-east-2.amazonaws.com/production",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
